/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CatalogPilotRouteImport } from './routes/catalog-pilot'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalDeliveryRouteImport } from './routes/digital-delivery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GamesRouteImport } from './routes/games'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminOwnerRouteImport } from './routes/admin.owner'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiReadinessRouteImport } from './routes/api/readiness'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as ApiShopifyGraphqlRouteImport } from './routes/api/shopify/graphql'
import { Route as ApiZidWebhooksRouteImport } from './routes/api/zid/webhooks'
import { Route as ApiPublicWebhooksHyperpayRouteImport } from './routes/api/public/webhooks/hyperpay'
import { Route as ApiPublicWebhooksMoyasarRouteImport } from './routes/api/public/webhooks/moyasar'
import { Route as ApiPublicWebhooksTapRouteImport } from './routes/api/public/webhooks/tap'
import { Route as ApiPublicWebhooksTelrRouteImport } from './routes/api/public/webhooks/telr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogPilotRoute = CatalogPilotRouteImport.update({
  id: '/catalog-pilot',
  path: '/catalog-pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalDeliveryRoute = DigitalDeliveryRouteImport.update({
  id: '/digital-delivery',
  path: '/digital-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnerRoute = AdminOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadinessRoute = ApiReadinessRouteImport.update({
  id: '/api/readiness',
  path: '/api/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifyGraphqlRoute = ApiShopifyGraphqlRouteImport.update({
  id: '/api/shopify/graphql',
  path: '/api/shopify/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZidWebhooksRoute = ApiZidWebhooksRouteImport.update({
  id: '/api/zid/webhooks',
  path: '/api/zid/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksHyperpayRoute =
  ApiPublicWebhooksHyperpayRouteImport.update({
    id: '/api/public/webhooks/hyperpay',
    path: '/api/public/webhooks/hyperpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMoyasarRoute =
  ApiPublicWebhooksMoyasarRouteImport.update({
    id: '/api/public/webhooks/moyasar',
    path: '/api/public/webhooks/moyasar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTapRoute = ApiPublicWebhooksTapRouteImport.update({
  id: '/api/public/webhooks/tap',
  path: '/api/public/webhooks/tap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksTelrRoute = ApiPublicWebhooksTelrRouteImport.update({
  id: '/api/public/webhooks/telr',
  path: '/api/public/webhooks/telr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/catalog-pilot': typeof CatalogPilotRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/digital-delivery': typeof DigitalDeliveryRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/owner': typeof AdminOwnerRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/health': typeof ApiHealthRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/item/$id': typeof ItemIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/api/zid/webhooks': typeof ApiZidWebhooksRoute
  '/api/public/webhooks/hyperpay': typeof ApiPublicWebhooksHyperpayRoute
  '/api/public/webhooks/moyasar': typeof ApiPublicWebhooksMoyasarRoute
  '/api/public/webhooks/tap': typeof ApiPublicWebhooksTapRoute
  '/api/public/webhooks/telr': typeof ApiPublicWebhooksTelrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/catalog-pilot': typeof CatalogPilotRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/digital-delivery': typeof DigitalDeliveryRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/owner': typeof AdminOwnerRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/health': typeof ApiHealthRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/item/$id': typeof ItemIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/api/zid/webhooks': typeof ApiZidWebhooksRoute
  '/api/public/webhooks/hyperpay': typeof ApiPublicWebhooksHyperpayRoute
  '/api/public/webhooks/moyasar': typeof ApiPublicWebhooksMoyasarRoute
  '/api/public/webhooks/tap': typeof ApiPublicWebhooksTapRoute
  '/api/public/webhooks/telr': typeof ApiPublicWebhooksTelrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/catalog-pilot': typeof CatalogPilotRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/digital-delivery': typeof DigitalDeliveryRoute
  '/faq': typeof FaqRoute
  '/games': typeof GamesRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/owner': typeof AdminOwnerRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/staff': typeof AdminStaffRoute
  '/api/health': typeof ApiHealthRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/item/$id': typeof ItemIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/api/zid/webhooks': typeof ApiZidWebhooksRoute
  '/api/public/webhooks/hyperpay': typeof ApiPublicWebhooksHyperpayRoute
  '/api/public/webhooks/moyasar': typeof ApiPublicWebhooksMoyasarRoute
  '/api/public/webhooks/tap': typeof ApiPublicWebhooksTapRoute
  '/api/public/webhooks/telr': typeof ApiPublicWebhooksTelrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/cart'
    | '/catalog'
    | '/catalog-pilot'
    | '/checkout'
    | '/contact'
    | '/digital-delivery'
    | '/faq'
    | '/games'
    | '/offers'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/success'
    | '/terms'
    | '/account'
    | '/orders'
    | '/wallet'
    | '/admin/analytics'
    | '/admin/codes'
    | '/admin/finance'
    | '/admin/integrations'
    | '/admin/owner'
    | '/admin/security'
    | '/admin/staff'
    | '/api/health'
    | '/api/readiness'
    | '/item/$id'
    | '/admin/'
    | '/api/shopify/graphql'
    | '/api/zid/webhooks'
    | '/api/public/webhooks/hyperpay'
    | '/api/public/webhooks/moyasar'
    | '/api/public/webhooks/tap'
    | '/api/public/webhooks/telr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cards'
    | '/cart'
    | '/catalog'
    | '/catalog-pilot'
    | '/checkout'
    | '/contact'
    | '/digital-delivery'
    | '/faq'
    | '/games'
    | '/offers'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/success'
    | '/terms'
    | '/account'
    | '/orders'
    | '/wallet'
    | '/admin/analytics'
    | '/admin/codes'
    | '/admin/finance'
    | '/admin/integrations'
    | '/admin/owner'
    | '/admin/security'
    | '/admin/staff'
    | '/api/health'
    | '/api/readiness'
    | '/item/$id'
    | '/admin'
    | '/api/shopify/graphql'
    | '/api/zid/webhooks'
    | '/api/public/webhooks/hyperpay'
    | '/api/public/webhooks/moyasar'
    | '/api/public/webhooks/tap'
    | '/api/public/webhooks/telr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/cart'
    | '/catalog'
    | '/catalog-pilot'
    | '/checkout'
    | '/contact'
    | '/digital-delivery'
    | '/faq'
    | '/games'
    | '/offers'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/subscriptions'
    | '/success'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/orders'
    | '/_authenticated/wallet'
    | '/admin/analytics'
    | '/admin/codes'
    | '/admin/finance'
    | '/admin/integrations'
    | '/admin/owner'
    | '/admin/security'
    | '/admin/staff'
    | '/api/health'
    | '/api/readiness'
    | '/item/$id'
    | '/admin/'
    | '/api/shopify/graphql'
    | '/api/zid/webhooks'
    | '/api/public/webhooks/hyperpay'
    | '/api/public/webhooks/moyasar'
    | '/api/public/webhooks/tap'
    | '/api/public/webhooks/telr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CardsRoute: typeof CardsRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CatalogPilotRoute: typeof CatalogPilotRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DigitalDeliveryRoute: typeof DigitalDeliveryRoute
  FaqRoute: typeof FaqRoute
  GamesRoute: typeof GamesRoute
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadinessRoute: typeof ApiReadinessRoute
  ItemIdRoute: typeof ItemIdRoute
  ApiShopifyGraphqlRoute: typeof ApiShopifyGraphqlRoute
  ApiZidWebhooksRoute: typeof ApiZidWebhooksRoute
  ApiPublicWebhooksHyperpayRoute: typeof ApiPublicWebhooksHyperpayRoute
  ApiPublicWebhooksMoyasarRoute: typeof ApiPublicWebhooksMoyasarRoute
  ApiPublicWebhooksTapRoute: typeof ApiPublicWebhooksTapRoute
  ApiPublicWebhooksTelrRoute: typeof ApiPublicWebhooksTelrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog-pilot': {
      id: '/catalog-pilot'
      path: '/catalog-pilot'
      fullPath: '/catalog-pilot'
      preLoaderRoute: typeof CatalogPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-delivery': {
      id: '/digital-delivery'
      path: '/digital-delivery'
      fullPath: '/digital-delivery'
      preLoaderRoute: typeof DigitalDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owner': {
      id: '/admin/owner'
      path: '/owner'
      fullPath: '/admin/owner'
      preLoaderRoute: typeof AdminOwnerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/readiness': {
      id: '/api/readiness'
      path: '/api/readiness'
      fullPath: '/api/readiness'
      preLoaderRoute: typeof ApiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/graphql': {
      id: '/api/shopify/graphql'
      path: '/api/shopify/graphql'
      fullPath: '/api/shopify/graphql'
      preLoaderRoute: typeof ApiShopifyGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zid/webhooks': {
      id: '/api/zid/webhooks'
      path: '/api/zid/webhooks'
      fullPath: '/api/zid/webhooks'
      preLoaderRoute: typeof ApiZidWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/hyperpay': {
      id: '/api/public/webhooks/hyperpay'
      path: '/api/public/webhooks/hyperpay'
      fullPath: '/api/public/webhooks/hyperpay'
      preLoaderRoute: typeof ApiPublicWebhooksHyperpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/moyasar': {
      id: '/api/public/webhooks/moyasar'
      path: '/api/public/webhooks/moyasar'
      fullPath: '/api/public/webhooks/moyasar'
      preLoaderRoute: typeof ApiPublicWebhooksMoyasarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/tap': {
      id: '/api/public/webhooks/tap'
      path: '/api/public/webhooks/tap'
      fullPath: '/api/public/webhooks/tap'
      preLoaderRoute: typeof ApiPublicWebhooksTapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/telr': {
      id: '/api/public/webhooks/telr'
      path: '/api/public/webhooks/telr'
      fullPath: '/api/public/webhooks/telr'
      preLoaderRoute: typeof ApiPublicWebhooksTelrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminOwnerRoute: typeof AdminOwnerRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminOwnerRoute: AdminOwnerRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CardsRoute: CardsRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CatalogPilotRoute: CatalogPilotRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DigitalDeliveryRoute: DigitalDeliveryRoute,
  FaqRoute: FaqRoute,
  GamesRoute: GamesRoute,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadinessRoute: ApiReadinessRoute,
  ItemIdRoute: ItemIdRoute,
  ApiShopifyGraphqlRoute: ApiShopifyGraphqlRoute,
  ApiZidWebhooksRoute: ApiZidWebhooksRoute,
  ApiPublicWebhooksHyperpayRoute: ApiPublicWebhooksHyperpayRoute,
  ApiPublicWebhooksMoyasarRoute: ApiPublicWebhooksMoyasarRoute,
  ApiPublicWebhooksTapRoute: ApiPublicWebhooksTapRoute,
  ApiPublicWebhooksTelrRoute: ApiPublicWebhooksTelrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
